export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USERS_SUCCESS = "CREATE_USERS_SUCCESS";
export const CREATE_USERS_ERROR = "CREATE_USERS_ERROR";

export const DELETE_USERS_REQUEST = "CREATE_USERS_ERROR";
export const DELETE_USERS_SUCCESS = "CREATE_USERS_ERROR";
export const DELETE_USERS_ERROR = "CREATE_USERS_ERROR";
